config/routes.rb
Rails.application.routes.draw do
  #get 'users/index'
  #get 'users/show'
  #get 'users/edit'
  #get 'user/show'
  # get 'books/show'
  # get 'books/index'
  # get 'books/new'
  # get 'books/edit'

  get 'home/about' => 'tops#about'

  devise_for :users

  resources :books

  resources :users

root "tops#home"





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user


validates :title, presence: true

validates :body, presence: true, length: { maximum: 200 }




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 validates :name, presence: true, length: {minimum: 2 ,maximum: 20}


 validates :introduction,  length: {maximum: 50}

 attachment :profile_image

 has_many :books, dependent: :destroy

 def email_required?
    false
  end
  def email_changed?
    false
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #strong parametersを設定し、usernameを許可
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password)}
  end

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後に遷移するpathを設定
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
before_action :correct_user,   only: [:edit, :update]



  def show
  	@booknew = Book.new
  	@user = current_user
  	@book = Book.find(params[:id])



  end
  #  一覧機能
  def index
		@book = Book.new

        @books = Book.all
        # createアクションを呼び出す
        @user = current_user

  end


def create
	@book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
       flash[:notice] = "You have creatad book successfully."
    redirect_to book_path(@book.id)
	else
	@books = Book.all
	@user = current_user
	render 'books/index'
	end


end






  def edit

  	@book = Book.find(params[:id])




  end


  def destroy
          book = Book.find(params[:id])
          book.destroy
          redirect_to books_path


        end


def update

	@book =Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to book_path(@book.id)
    else
    render 'books/edit'


    end

end





private


 def book_params
	params.require(:book).permit(:title, :body)

 end



 def correct_user
           book = Book.find(params[:id])
           if current_user != book.user
           redirect_to books_path
           end

        end



end

app/controllers/tops_controller.rb
class TopsController < ApplicationController



def  home


end


def about


end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]




  def index

    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
  	@user = current_user
    @book = Book.new
    @user = User.find(params[:id])
    @booksecond = @user.books


  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
     	flash[:notice] = "You have updated user successfully."

        redirect_to user_path(@user.id)
     else
     	 render 'users/edit'
     end

  end
  def create
	book = Book.new(book_params)
           book.save
           redirect_to book_path

   end





		  private

			  def user_params
				params.require(:user).permit(:name,:introduction,:profile_image)

			  end


		    def correct_user
		       user = User.find(params[:id])
		       if current_user != user
		       redirect_to user_path(current_user)
		       end

		    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
	  <h3> <%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     <% end %>









<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
<h4>Title</h4>

<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<br>

<%= f.submit 'Update Book', class: 'btn btn-primary'%>

<% end %>


<p>
 <%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
<div class='container'>
<div class='row'>

<div>
<%= render"users/list", user: @user, book: @book %>
</div>


	<% if @book.errors.any? %>
	  <h3> <%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     <% end %>



<div class='col-xs-9'>
<h2>Books</h2>
	<table class="table table-hover">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>

			<% @books.each do |book| %>
				<tr>
					<td><%= link_to user_path(book.user_id) do %>
						<%= attachment_image_tag book.user , :profile_image, :fill, 100, 100, format: 'jpeg' %>
					<% end %></td>
					<td><%= link_to book.title, book_path(book) %></td>
					<td><%= book.body %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

</div>



</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class='container'>
<div class='row'>

<div>
<%= render"users/list", user: @book.user, book: @booknew %>
</div>


 <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
			<tbody>
		  <tr>
		  	        <td>
		  	　　　　  <%= link_to user_path(@book.user) do %>
		  	        <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg"  %>
		  	        <br>
		  	        <%= @book.user.name %>
		  	        <% end %>
		  	        </td>

					<td><%= @book.title %></td>
					<td><%= @book.body %></td>
						<% if current_user.id == @book.user_id %>
  							<div>
 								<td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
			        			<td><%= link_to "Destroy", book_path(@book), method: :delete,data: {confirm: "本当に消しますか？"} ,class: "btn btn-danger" %></td>
  							</div>
  						</tr>
  						<tr>

  						</tr>
						<% else %>
						<% end %>

          </tr>
  </body>
    </table>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <header class="navbar navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nav navbar-left' >
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to " Home", user_path(current_user) , class: "glyphicon glyphicon-home" %></li>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %></li>
            <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %></li>
            <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
          <% else %>
            <li><%= link_to " Home", root_path , class: "glyphicon glyphicon-home" %></li>
            <li><%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
            <li><%= link_to " login ", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
   </header>

  <div class="flash">
    <%= flash[:notice] %>
    </div>




    <%= yield %>
</body>
 <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>


</html>

app/views/tops/about.html.erb
    <div class='body'>
      <div class='container'>

        <p id="notice"></p>


        <h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

    <footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
      </div>
    </div>
  </div>
</footer>


  </body>

app/views/tops/home.html.erb
  <body>
   

  	<div class='body'>
      <div class='container'>

        <p id="notice"></p>


      	<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
            
  </div>
</div>
        

      </div>
    </div>


  </body>
</html>

app/views/users/_list.html.erb
    <div class = "col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"  %>
    <table class='table'>
     <tbody>
      <tr>
    	  <th>name</th>
    	  </th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>





	  <%= link_to " ", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>



<h2>New book</h2>

 <%= form_for(book) do |f| %>

<h4>Title</h4>
	<%= f.text_field :title %>




<h4>Opinion</h4>

    <%= f.text_area :body %>


<%= f.submit 'Create Book', class: 'btn btn-primary btn-block'%>

<% end %>

</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
      <h3> <%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>




<h2>User info</h2>

<%= form_for(@user) do |f| %>
	<p>Name</p>
	<%= f.text_field :name %>


	<p>Image</p>
    <%=  f.attachment_field :profile_image %>

    <p>introduction</p>
    <%= f.text_area :introduction %>

<br>
    <%= f.submit 'Update User' %>





<% end %>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>

<div>
<%= render "users/list", user: @user, book: @book %>
</div>

 <div class='col-xs-9'>
    <h2>Users</h2>

    <table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
      <tr>

          <td><%= attachment_image_tag user , :profile_image, :fill, 100, 100, format: 'jpeg' %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user)%></td>

           <% end %>
      </tr>
  </tbody>
</table>

  </div>

</div>

</div>

app/views/users/show.html.erb
<div class='container'>
<div class='row'>
<div>
<%= render"users/list", user: @user, book: @book %>
</div>

<div class = "col-xs-9">
<h2>Books</h2>

<table class="table table-hover table-inverse">
  <thead>
<tr>
	  <th></th>
      <th>Title</th>
      <th>Opinion</th>
</tr>
  </thead>
  <tbody>

	    <% @booksecond.each do |book| %>
	    <tr>
						<td><%= attachment_image_tag book.user , :profile_image, :fill, 50, 50, format: 'jpeg' %></td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
        </tr>
				<% end %>

 	
  </tbody>
</table>

  </div>

  </div>
  </div>